# Generated by Django 3.1.1 on 2020-12-11 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmall', '0003_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='province',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='province',
        ),
    ]
