# Generated by Django 3.1.1 on 2020-12-11 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmall', '0004_auto_20201212_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shoppingmall.province'),
        ),
        migrations.AddField(
            model_name='seller',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shoppingmall.province'),
        ),
    ]
