# Generated by Django 3.1.1 on 2020-12-13 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmall', '0005_auto_20201212_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='referral_fee',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='shop',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=8),
        ),
    ]
