# Generated by Django 3.1.1 on 2020-12-14 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmall', '0006_auto_20201214_0831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='referral_fee',
            new_name='referral_rate',
        ),
        migrations.AddField(
            model_name='order',
            name='total_referral_fee',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='referral_fee',
            field=models.FloatField(default=0.0),
        ),
    ]
