# Generated by Django 3.1.1 on 2020-12-19 04:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import shoppingmall.models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmall', '0008_auto_20201214_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='receipt',
            field=models.ImageField(null=True, upload_to=shoppingmall.models.receipt_directory_path),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('referral_rate', models.FloatField(verbose_name=0.0)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_created')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingmall.category')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingmall.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingmall.admin')),
            ],
        ),
    ]
