# Generated by Django 3.1.1 on 2020-12-21 15:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import shoppingmall.models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmall', '0009_auto_20201219_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.ImageField(null=True, upload_to=shoppingmall.models.announcement_image_directory_path),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='type',
            field=models.CharField(blank=True, choices=[('message', 'message'), ('image', 'image'), ('video', 'Video')], max_length=10),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='video',
            field=models.FileField(null=True, upload_to=shoppingmall.models.announcement_video_directory_path),
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('all', 'All'), ('filter', 'Filter')], default='all', max_length=10)),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('uz', 'Uzbek'), ('kr', 'Korean')], default='uz', max_length=5)),
                ('age_from', models.IntegerField(default=0)),
                ('age_to', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_created')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shoppingmall.province')),
            ],
        ),
        migrations.AddField(
            model_name='announcement',
            name='filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shoppingmall.filter'),
        ),
    ]
