# Generated by Django 3.1.1 on 2020-12-21 16:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmall', '0010_auto_20201222_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DeliveredAnnouncement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('is_failed', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_created')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingmall.announcement')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingmall.customer')),
            ],
        ),
    ]
