# Generated by Django 3.1.1 on 2020-12-24 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmall', '0011_auto_20201222_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='video',
        ),
        migrations.RemoveField(
            model_name='filter',
            name='age_from',
        ),
        migrations.RemoveField(
            model_name='filter',
            name='age_to',
        ),
        migrations.AddField(
            model_name='announcement',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shoppingmall.product'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('uz', 'Uzbek'), ('kr', 'Korean')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='province',
            field=models.IntegerField(null=True),
        ),
    ]
