# Generated by Django 3.1.1 on 2020-12-24 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmall', '0012_auto_20201224_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='type',
            field=models.CharField(blank=True, choices=[('message', 'message'), ('image', 'image'), ('video', 'Video'), ('product', 'Product')], max_length=10),
        ),
    ]
