# Generated by Django 3.1.1 on 2020-12-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmall', '0013_auto_20201224_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='end_at'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start_at'),
        ),
    ]
