# Generated by Django 3.1.1 on 2020-12-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmall', '0014_auto_20201224_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='total_target_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
