# Generated by Django 3.1.1 on 2020-12-26 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmall', '0016_auto_20201226_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='organization',
        ),
        migrations.AddField(
            model_name='seller',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shoppingmall.shop'),
        ),
    ]
