# Generated by Django 3.1.1 on 2020-12-26 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmall', '0017_auto_20201226_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='organization',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
