# Generated by Django 3.1.1 on 2020-12-26 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmall', '0018_auto_20201226_1604'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deliverypolicy',
            unique_together={('shop', 'type', 'unit_from', 'unit_to')},
        ),
    ]
