# Generated by Django 3.1.1 on 2020-12-27 13:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmall', '0019_auto_20201227_0220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('cancel', 'Cancel')], default='P', max_length=20)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_created')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingmall.shop')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('cancel', 'Cancel')], default='P', max_length=100),
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_created')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingmall.invoice')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingmall.order')),
            ],
        ),
    ]
