# Generated by Django 3.1.1 on 2020-12-28 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmall', '0021_auto_20201227_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='accepted_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shoppingmall.invoice'),
        ),
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
    ]
