# Generated by Django 3.1.1 on 2020-12-29 08:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmall', '0023_invoice_invoice_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent_id',
        ),
        migrations.RemoveField(
            model_name='category',
            name='referral_rate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='localize',
            name='type',
            field=models.CharField(blank=True, choices=[('classification', 'Classification'), ('category', 'Category'), ('subproduct', 'Subproduct'), ('product', 'Product'), ('collection', 'Collection')], max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='made_in',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Subproduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_created')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shoppingmall.category')),
                ('titles', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shoppingmall.localize')),
            ],
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('referral_rate', models.FloatField(default=0.0)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_created')),
                ('titles', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shoppingmall.localize')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='classification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shoppingmall.classification'),
        ),
        migrations.AddField(
            model_name='product',
            name='subproduct',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shoppingmall.subproduct'),
        ),
    ]
