# Generated by Django 3.1.1 on 2021-01-09 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmall', '0025_auto_20210109_1155'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deliverypolicy',
            unique_together={('shop', 'unit_from', 'unit_to')},
        ),
        migrations.RemoveField(
            model_name='deliverypolicy',
            name='type',
        ),
    ]
