# Generated by Django 3.1.1 on 2021-01-09 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmall', '0026_auto_20210109_1855'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deliverypolicy',
            unique_together={('shop', 'unit_from')},
        ),
    ]
