# Generated by Django 3.1.1 on 2021-01-26 14:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmall', '0030_product_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopconfig',
            name='telegram_users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, null=True, size=None),
        ),
    ]
