# Generated by Django 3.1.1 on 2021-05-01 16:38

from django.db import migrations, models
import shoppingmall.models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmall', '0031_shopconfig_telegram_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_app',
            field=models.ImageField(null=True, upload_to=shoppingmall.models.category_photo_directory_path),
        ),
        migrations.AddField(
            model_name='category',
            name='image_tg',
            field=models.ImageField(null=True, upload_to=shoppingmall.models.category_photo_directory_path),
        ),
        migrations.AddField(
            model_name='classification',
            name='image_app',
            field=models.ImageField(null=True, upload_to=shoppingmall.models.category_photo_directory_path),
        ),
        migrations.AddField(
            model_name='classification',
            name='image_tg',
            field=models.ImageField(null=True, upload_to=shoppingmall.models.category_photo_directory_path),
        ),
        migrations.AddField(
            model_name='subproduct',
            name='image_app',
            field=models.ImageField(null=True, upload_to=shoppingmall.models.category_photo_directory_path),
        ),
        migrations.AddField(
            model_name='subproduct',
            name='image_tg',
            field=models.ImageField(null=True, upload_to=shoppingmall.models.category_photo_directory_path),
        ),
    ]
